### GET request
GET http://localhost:8280

### GET all contents
GET http://localhost:8280/api/content/all

### GET content with id=1
GET http://localhost:8280/api/content/1
### GET content with id=2
GET http://localhost:8280/api/content/2

### Create new content
POST http://localhost:8280/api/content
Content-type: application/json

{
  "id": 2,
  "title": "My second blog post",
  "description": "This is the description of my second blog post",
  "status": "IDEA",
  "contentType": "VIDEO",
  "dateCrated": "2025-12-08T15:47:11.1236068",
  "dateUpdated": null,
  "url": ""
}

### Update content with id=1
PUT http://localhost:8280/api/content/1
Content-type: application/json

{
  "id": 1,
  "title": "MY FIRST BLOG POST!!!",
  "description": "This is the description of my second blog post",
  "status": "IDEA",
  "contentType": "VIDEO",
  "dateCrated": "2025-12-08T15:47:11.1236068",
  "dateUpdated": "2025-12-08T17:47:11.1236068",
  "url": ""
}

### DELETE content with id=2
DELETE http://localhost:8280/api/content/2

