# logging
logging.level.org.springframework.jdbc=DEBUG

cc.welcomeMessage=Welcome to the Content Calendar Application in Dev Mode!
cc.about=This application helps you manage your content calendar effectively.